"""Initial migration with all DJ platform models

Revision ID: 1122a1baa528
Revises: 
Create Date: 2025-11-06 17:16:55.032225+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1122a1baa528'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('dj_name', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dj_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('tracklist', sa.JSON(), nullable=True),
    sa.Column('transitions', sa.JSON(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('dj_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dj_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dj_sets_dj', 'dj_sets', ['dj_id'], unique=False)
    op.create_index('idx_dj_sets_genre', 'dj_sets', ['genre'], unique=False)
    op.create_index('idx_dj_sets_recorded', 'dj_sets', ['recorded_at'], unique=False)
    op.create_table('playlists',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('total_duration', sa.Float(), nullable=False),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlists_public', 'playlists', ['is_public'], unique=False)
    op.create_index('idx_playlists_user', 'playlists', ['user_id'], unique=False)
    op.create_table('stations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('genre', sa.String(length=50), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('stream_url', sa.String(length=500), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('total_listeners', sa.Integer(), nullable=False),
    sa.Column('peak_listeners', sa.Integer(), nullable=False),
    sa.Column('total_plays', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stations_genre', 'stations', ['genre'], unique=False)
    op.create_index('idx_stations_live', 'stations', ['is_live'], unique=False)
    op.create_index('idx_stations_owner', 'stations', ['owner_id'], unique=False)
    op.create_index('idx_stations_slug', 'stations', ['slug'], unique=False)
    op.create_index(op.f('ix_stations_slug'), 'stations', ['slug'], unique=True)
    op.create_table('tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('artist', sa.String(length=255), nullable=False),
    sa.Column('album', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('bpm', sa.Float(), nullable=True),
    sa.Column('key', sa.String(length=10), nullable=True),
    sa.Column('energy', sa.Float(), nullable=True),
    sa.Column('danceability', sa.Float(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('file_format', sa.String(length=10), nullable=True),
    sa.Column('waveform_data', sa.JSON(), nullable=True),
    sa.Column('spectral_data', sa.JSON(), nullable=True),
    sa.Column('play_count', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('uploader_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracks_artist', 'tracks', ['artist'], unique=False)
    op.create_index('idx_tracks_bpm', 'tracks', ['bpm'], unique=False)
    op.create_index('idx_tracks_genre', 'tracks', ['genre'], unique=False)
    op.create_index('idx_tracks_key', 'tracks', ['key'], unique=False)
    op.create_index('idx_tracks_title', 'tracks', ['title'], unique=False)
    op.create_index('idx_tracks_uploader', 'tracks', ['uploader_id'], unique=False)
    op.create_table('playlist_tracks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('playlist_id', sa.UUID(), nullable=False),
    sa.Column('track_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_playlist_tracks_playlist', 'playlist_tracks', ['playlist_id'], unique=False)
    op.create_index('idx_playlist_tracks_position', 'playlist_tracks', ['playlist_id', 'position'], unique=False)
    op.create_table('streaming_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('peak_listeners', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Float(), nullable=True),
    sa.Column('data_transferred', sa.Integer(), nullable=False),
    sa.Column('bitrate', sa.Integer(), nullable=False),
    sa.Column('stream_key', sa.String(length=255), nullable=True),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_streaming_sessions_started', 'streaming_sessions', ['started_at'], unique=False)
    op.create_index('idx_streaming_sessions_station', 'streaming_sessions', ['station_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_streaming_sessions_station', table_name='streaming_sessions')
    op.drop_index('idx_streaming_sessions_started', table_name='streaming_sessions')
    op.drop_table('streaming_sessions')
    op.drop_index('idx_playlist_tracks_position', table_name='playlist_tracks')
    op.drop_index('idx_playlist_tracks_playlist', table_name='playlist_tracks')
    op.drop_table('playlist_tracks')
    op.drop_index('idx_tracks_uploader', table_name='tracks')
    op.drop_index('idx_tracks_title', table_name='tracks')
    op.drop_index('idx_tracks_key', table_name='tracks')
    op.drop_index('idx_tracks_genre', table_name='tracks')
    op.drop_index('idx_tracks_bpm', table_name='tracks')
    op.drop_index('idx_tracks_artist', table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_stations_slug'), table_name='stations')
    op.drop_index('idx_stations_slug', table_name='stations')
    op.drop_index('idx_stations_owner', table_name='stations')
    op.drop_index('idx_stations_live', table_name='stations')
    op.drop_index('idx_stations_genre', table_name='stations')
    op.drop_table('stations')
    op.drop_index('idx_playlists_user', table_name='playlists')
    op.drop_index('idx_playlists_public', table_name='playlists')
    op.drop_table('playlists')
    op.drop_index('idx_dj_sets_recorded', table_name='dj_sets')
    op.drop_index('idx_dj_sets_genre', table_name='dj_sets')
    op.drop_index('idx_dj_sets_dj', table_name='dj_sets')
    op.drop_table('dj_sets')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###